// Strings in different languages
const language = {

    // English
    en: {

        document_title:                        "Geiger counter | GMT Geiger Counter",
        geiger_counter:                        "Geiger counter",
        equivalent_doses:                      "Equivalent doses",
        radiation_rating:                      "Radiation rating",
        radiation_history:                     "Radiation history",
        tube_statistics:                       "Tube statistics",
        tube_info:                             "Tube info",
        total_counts:                          "Total counts",
        number_of_tubes:                       "Number of tubes",
        tube_type:                             "Tube type",
        main_tube:                             "Main tube",
        follower_tube:                         "Follower tube",
        counts:                                "Counts",
        relative:                              "Relative",
        settings:                              "Settings",
        unit_settings:                         "Unit settings",
        auto_range_units:                      "Auto range units",
        main_screen_unit:                      "Main screen unit",
        sieverts:                              "Sieverts",
        rem:                                   "Rem",
        rontgen:                               "Röntgen",
        gray:                                  "Gray",
        update_interval:                       "Update interval",
        refresh_rate:                          "Refresh rate",
        vertical_steps:                        "Vertical steps",
        horizontal_steps:                      "Horizontal steps",
        smoothing_factor:                      "Smoothing factor",
        save_history:                          "Save history",
        actions:                               "Actions",
        download_log:                          "Download log",
        restart_system_title:                  "Restart system",
        counts_per_minute_abbreviation:        "CPM",
        counts_per_second_abbreviation:        "CPS",
        micro_prefix:                          "µ",
        milli_prefix:                          "m",
        sieverts_per_hour_abbreviation:        "Sv/h",
        rem_per_hour_abbreviation:             "rem/h",
        rontgen_per_hour_abbreviation:         "R/h",
        gray_per_hour_abbreviation:            "Gy/h",
        radiation_rating_normal_title:         "NORMAL",
        radiation_rating_normal_description:   "Normal background radiation, no action is needed.",
        radiation_rating_elevated_title:       "ELEVATED",
        radiation_rating_elevated_description: "Slightly elevated radiation readings, no immediate danger.",
        radiation_rating_medium_title:         "MEDIUM",
        radiation_rating_medium_description:   "Medium level of radiation, closely monitor readings and prepare to leave.",
        radiation_rating_high_title:           "HIGH",
        radiation_rating_high_description:     "High radiation exposure! Leave the area as fast as possible.",
        radiation_rating_extreme_title:        "EXTREME",
        radiation_rating_extreme_description:  "EXTREME DANGER! Evacuate immediately! Radiation readings are extremely high.",
        radiation_rating_unknown_title:        "UNKNOWN",
        radiation_rating_unknown_description:  "Unknown radiation rating, which is indicative of a communication error.",
        data_request_failed:                   "Data request failed!",
        data_request_failed_message:           "Requesting the required data failed! Please check the wireless connection.",
        go_back:                               "Go back",
        refresh:                               "Refresh",
        geiger_counter_disabled:               "Geiger counter is disabled!",
        geiger_counter_disabled_message:       "The Geiger counter is disabled! Please enable it before using this feature.",
        second_abbreviation:                   "s",
        minute_abbreviation:                   "m",
        hour_abbreviation:                     "h",
        restart_system:                        "Restart system?",
        restart_system_message:                "Restart the system? Keep in mind that restarting the system will reset all data that has been recorded so far.",
        yes:                                   "Yes",
        no:                                    "No",
        unknown_error:                         "Unknown error!",
        unknown_error_message:                 "An unknown error occurred! Please refresh the interface."

    },

    // German
    de: {

        document_title:                        "Geigerzähler | GMT Geiger Counter",
        geiger_counter:                        "Geigerzähler",
        equivalent_doses:                      "Äquivalenzdosen",
        radiation_rating:                      "Strahlungsbewertung",
        radiation_history:                     "Strahlungsverlauf",
        tube_statistics:                       "Röhrenstatistik",
        tube_info:                             "Röhreninfo",
        total_counts:                          "Alle Zählungen",
        number_of_tubes:                       "Anzahl der Röhren",
        tube_type:                             "Röhrentyp",
        main_tube:                             "Hauptröhre",
        follower_tube:                         "Nebenröhre",
        counts:                                "Zählungen",
        relative:                              "Relativ",
        settings:                              "Einstellungen",
        unit_settings:                         "Einheitseinstelllungen",
        auto_range_units:                      "Auto-Range Einheiten",
        main_screen_unit:                      "Displayeinheit",
        sieverts:                              "Sieverts",
        rem:                                   "Rem",
        rontgen:                               "Röntgen",
        gray:                                  "Gray",
        update_interval:                       "Updateintervall",
        refresh_rate:                          "Aktualisierungsrate",
        vertical_steps:                        "Vertikale Schritte",
        horizontal_steps:                      "Horizontale Schritte",
        smoothing_factor:                      "Glättungsfaktor",
        save_history:                          "Verlauf speichern",
        actions:                               "Aktionen",
        download_log:                          "Logdatei downloaden",
        restart_system_title:                  "System neu starten",
        counts_per_minute_abbreviation:        "CPM",
        counts_per_second_abbreviation:        "CPS",
        micro_prefix:                          "µ",
        milli_prefix:                          "m",
        sieverts_per_hour_abbreviation:        "Sv/h",
        rem_per_hour_abbreviation:             "rem/h",
        rontgen_per_hour_abbreviation:         "R/h",
        gray_per_hour_abbreviation:            "Gy/h",
        radiation_rating_normal_title:         "NORMAL",
        radiation_rating_normal_description:   "Normale Hintergrundstrahlung, es ist keine Aktion erforderlich.",
        radiation_rating_elevated_title:       "LEICHT ERHÖHT",
        radiation_rating_elevated_description: "Leicht erhöhte Strahlungsmessung, keine unmittelbare Gefahr.",
        radiation_rating_medium_title:         "MITTEL",
        radiation_rating_medium_description:   "Mittlere Strahlungswerte, beobachten Sie die Messungen genau und bereiten Sie sich darauf vor, den Bereich zu verlassen.",
        radiation_rating_high_title:           "HOCH",
        radiation_rating_high_description:     "Hohe Strahlungswerte! Verlassen Sie den Bereich so schnell wie möglich.",
        radiation_rating_extreme_title:        "EXTREM",
        radiation_rating_extreme_description:  "EXTREME GEFAHR! Sofort evakuieren! Die Strahlungswerte sind extrem hoch.",
        radiation_rating_unknown_title:        "UNBEKANNT",
        radiation_rating_unknown_description:  "Unbekannt, womöglich liegt ein Kommunikationsfehler vor.",
        data_request_failed:                   "Datenübertragung fehlgeschlagen!",
        data_request_failed_message:           "Die Anfrage der benötigten Daten ist fehlgeschlagen! Bitte überprüfen Sie die WLAN-Verbindung.",
        go_back:                               "Zurück",
        refresh:                               "Neuladen",
        geiger_counter_disabled:               "Geigerzähler ist deaktiviert!",
        geiger_counter_disabled_message:       "Der Geigerzähler ist deaktiviert! Bitte aktivieren Sie ihn, bevor Sie diese Funktion verwenden.",
        second_abbreviation:                   "s",
        minute_abbreviation:                   "m",
        hour_abbreviation:                     "h",
        restart_system:                        "System neu starten?",
        restart_system_message:                "System neu starten? Beachten Sie, dass durch einen Neustart des Systems alle bisher aufgezeichneten Daten zurückgesetzt werden.",
        yes:                                   "Ja",
        no:                                    "Nein",
        unknown_error:                         "Unbekannter Fehler!",
        unknown_error_message:                 "Ein unbekannter Fehler ist aufgetreten! Bitte aktualisieren Sie die Benutzeroberfläche."

    }

};

// Set strings based on the browser language or fall back to english
let string = language[navigator.language.slice(0, 2)] || language["en"];