#ifndef _STRINGS_ENGLISH_H
#define _STRINGS_ENGLISH_H

#define STRING_GEIGER_COUNTER_SCREEN_TITLE          "Beta & Gamma - GMT Geiger Counter"
#define STRING_GEIGER_COUNTER_SETTINGS_SCREEN_TITLE "Geiger counter settings"
#define STRING_AUTO_RANGE                           "Auto range"
#define STRING_SIEVERTS                             "Sievert"
#define STRING_REM                                  "Rem"
#define STRING_RONTGEN                              "Rontgen"
#define STRING_GRAY                                 "Gray"
#define STRING_RADIATION_RATING_NORMAL              "Normal"
#define STRING_RADIATION_RATING_ELEVATED            "Elevated"
#define STRING_RADIATION_RATING_MEDIUM              "Medium"
#define STRING_RADIATION_RATING_HIGH                "High"
#define STRING_RADIATION_RATING_EXTREME             "EXTREME"
#define STRING_MICRO_SIEVERTS_PER_HOUR_ABBREVIATION "uSv/h"
#define STRING_MILLI_SIEVERTS_PER_HOUR_ABBREVIATION "mSv/h"
#define STRING_SIEVERTS_PER_HOUR_ABBREVIATION       "Sv/h"
#define STRING_MICRO_REM_PER_HOUR_ABBREVIATION      "urem/h"
#define STRING_MILLI_REM_PER_HOUR_ABBREVIATION      "mrem/h"
#define STRING_REM_PER_HOUR_ABBREVIATION            "rem/h"
#define STRING_MICRO_RONTGEN_PER_HOUR_ABBREVIATION  "uR/h"
#define STRING_MILLI_RONTGEN_PER_HOUR_ABBREVIATION  "mR/h"
#define STRING_RONTGEN_PER_HOUR_ABBREVIATION        "R/h"
#define STRING_MICRO_GRAY_PER_HOUR_ABBREVIATION     "uGy/h"
#define STRING_MILLI_GRAY_PER_HOUR_ABBREVIATION     "mGy/h"
#define STRING_GRAY_PER_HOUR_ABBREVIATION           "Gy/h"
#define STRING_COUNTS_PER_MINUTE_ABBREVIATION       "CPM"
#define STRING_SECONDS_ABBREVIATION                 "s"
#define STRING_AUDIO_SETTINGS_TITLE                 "Audio settings"
#define STRING_TOGGLE_DETECTIONS                    "Detections"
#define STRING_TOGGLE_NOTIFICATIONS                 "Notifications"
#define STRING_TOGGLE_ALERTS                        "Alerts"
#define STRING_TOGGLE_INTERFACE                     "Interface"
#define STRING_TOGGLE_MUTE_EVERYTHING               "Mute everything"
#define STRING_DISPLAY_SETTINGS_TITLE               "Display settings"
#define STRING_TOGGLE_DISPLAY                       "Display"
#define STRING_AUTO_TIMEOUT                         "Auto timeout"
#define STRING_RADIATION_HISTORY_TITLE              "Radiation history (CPM)"
#define STRING_ROTATE_BY_90_DEGREES                 "Rotate by 90 degrees"
#define STRING_TAP_TO_CONTINUE                      "Tap to continue..."
#define STRING_COSMIC_RAY_DETECTOR_TITLE            "Cosmic ray detector"
#define STRING_COINCIDENCE_EVENTS                   "Coincidence Events"
#define STRING_COUNTS_PER_HOUR_ABBREVIATION         "CPH"
#define STRING_COUNTS                               "Counts"
#define STRING_TRUE_RNG_TITLE                       "True RNG"
#define STRING_INFO                                 "Info"
#define STRING_NOT_YET_AVAILABLE                    "Not yet available!"
#define STRING_HOTSPOT_SETTINGS_TITLE               "Hotspot settings"
#define STRING_ENABLE_HOTSPOT                       "Enable hotspot"
#define STRING_HOTSPOT_NAME                         "Hotspot name"
#define STRING_HOTSPOT_PASSWORD                     "Hotspot password"
#define STRING_IP_ADDRESS                           "IP address"
#define STRING_NON_APPLICABLE_ABBREVIATION          "N/A"
#define STRING_WIFI_SETTINGS_TITLE                  "WiFi settings"
#define STRING_ENABLE_WIFI                          "Enable WiFi"
#define STRING_WIFI_NAME                            "WiFi name"
#define STRING_WIFI_PASSWORD                        "WiFi password"
#define STRING_PASSWORD_HIDDEN                      "********"
#define STRING_CONNECTING                           "Connecting..."
#define STRING_SYSTEM_SETTINGS_TITLE                "System settings"
#define STRING_LOG_TO_SERIAL_CONSOLE                "Log to serial console"
#define STRING_LOG_TO_SD_CARD                       "Log to SD card"
#define STRING_LOG_SYSTEM_EVENT_MESSAGES            "Log system event messages"
#define STRING_LOG_SYSTEM_DATA                      "Log system data"
#define STRING_FIRMWARE_VERSION                     "Firmware version"

#endif