#ifndef _STRINGS_ENGLISH_H
#define _STRINGS_ENGLISH_H

#define STRING_GEIGER_COUNTER_SCREEN_TITLE    "Beta & Gamma - GMT Geiger Counter"
#define STRING_RADIATION_RATING_UNKNOWN       "Unkown"
#define STRING_RADIATION_RATING_NORMAL        "Normal"
#define STRING_RADIATION_RATING_ELEVATED      "Elevated"
#define STRING_RADIATION_RATING_HIGH          "High"
#define STRING_RADIATION_RATING_EXTREME       "EXTREME"
#define STRING_EQUIVALENT_DOSE_UNIT_USVH      "uSv/h"
#define STRING_COUNTS_PER_MINUTE_ABBREVIATION "CPM"
#define STRING_SECONDS_ABBREVIATION           "s"
#define STRING_AUDIO_SETTINGS_TITLE           "Audio settings"
#define STRING_TOGGLE_DETECTIONS              "Detections"
#define STRING_TOGGLE_NOTIFICATIONS           "Notifications"
#define STRING_TOGGLE_ALERTS                  "Alerts"
#define STRING_TOGGLE_INTERFACE               "Interface"
#define STRING_TOGGLE_MUTE_EVERYTHING         "Mute everything"
#define STRING_DISPLAY_SETTINGS_TITLE         "Display settings"
#define STRING_TOGGLE_DISPLAY                 "Display"
#define STRING_RADIATION_HISTORY_TITLE        "Radiation history (CPM)"
#define STRING_ROTATE_BY_90_DEGREES           "Rotate by 90 degrees"
#define STRING_TAP_TO_CONTINUE                "Tap to continue..."
#define STRING_COSMIC_RAY_DETECTOR_TITLE      "Cosmic ray detector"
#define STRING_COINCIDENCE_EVENTS             "Coincidence Events"
#define STRING_COUNTS_PER_HOUR_ABBREVIATION   "CPH"
#define STRING_COUNTS                         "Counts"
#define STRING_TRUE_RNG_TITLE                 "True RNG"
#define STRING_HOTSPOT_SETTINGS_TITLE         "Hotspot settings"
#define STRING_ENABLE_HOTSPOT                 "Enable hotspot"
#define STRING_HOTSPOT_NAME                   "Hotspot name"
#define STRING_HOTSPOT_PASSWORD               "Hotspot password"
#define STRING_WIFI_SETTINGS_TITLE            "WiFi settings"
#define STRING_SYSTEM_SETTINGS_TITLE          "System settings"
#define STRING_FIRMWARE_VERSION               "Firmware version"

#endif