#ifndef _STRINGS_ENGLISH_H
#define _STRINGS_ENGLISH_H

#define STRING_BETA_GAMMA_GMT_GEIGER_COUNTER        "Beta & Gamma - GMT Geiger Counter"
#define STRING_MICRO_SIEVERTS_PER_HOUR_ABBREVIATION "uSv/h"
#define STRING_MILLI_SIEVERTS_PER_HOUR_ABBREVIATION "mSv/h"
#define STRING_SIEVERTS_PER_HOUR_ABBREVIATION       "Sv/h"
#define STRING_MICRO_REM_PER_HOUR_ABBREVIATION      "urem/h"
#define STRING_MILLI_REM_PER_HOUR_ABBREVIATION      "mrem/h"
#define STRING_REM_PER_HOUR_ABBREVIATION            "rem/h"
#define STRING_MICRO_RONTGEN_PER_HOUR_ABBREVIATION  "uR/h"
#define STRING_MILLI_RONTGEN_PER_HOUR_ABBREVIATION  "mR/h"
#define STRING_RONTGEN_PER_HOUR_ABBREVIATION        "R/h"
#define STRING_MICRO_GRAY_PER_HOUR_ABBREVIATION     "uGy/h"
#define STRING_MILLI_GRAY_PER_HOUR_ABBREVIATION     "mGy/h"
#define STRING_GRAY_PER_HOUR_ABBREVIATION           "Gy/h"
#define STRING_NORMAL                               "Normal"
#define STRING_ELEVATED                             "Elevated"
#define STRING_MEDIUM                               "Medium"
#define STRING_HIGH                                 "High"
#define STRING_EXTREME                              "EXTREME"
#define STRING_COUNTS_PER_MINUTE_ABBREVIATION       "CPM"
#define STRING_SECONDS_ABBREVIATION                 "s"
#define STRING_GEIGER_COUNTER_INFO                  "Geiger counter info"
#define STRING_COUNTS                               "Counts"
#define STRING_ABSORBED_DOSE_MICRO_SIEVERTS         "Absorbed dose (uSv)"
#define STRING_MICRO_SIEVERTS_ABBREVIATION          "uSv"
#define STRING_AUTO_INTEGRATE                       "Auto integrate"
#define STRING_AUTO_RANGE                           "Auto range"
#define STRING_SIEVERTS                             "Sieverts"
#define STRING_REM                                  "Rem"
#define STRING_RONTGEN                              "Rontgen"
#define STRING_GRAY                                 "Gray"
#define STRING_AUDIO_SETTINGS                       "Audio settings"
#define STRING_DETECTIONS                           "Detections"
#define STRING_NOTIFICATIONS                        "Notifications"
#define STRING_ALERTS                               "Alerts"
#define STRING_INTERFACE                            "Interface"
#define STRING_MUTE_EVERYTHING                      "Mute everything"
#define STRING_DISPLAY_SETTINGS                     "Display settings"
#define STRING_DISPLAY                              "Display"
#define STRING_AUTO_TIMEOUT                         "Auto timeout"
#define STRING_RGB_LED                              "RGB LED"
#define STRING_COSMIC_RAY_DETECTOR                  "Cosmic ray detector"
#define STRING_ROTATE_BY_90_DEGREES                 "Rotate by 90 degrees"
#define STRING_TAP_TO_CONTINUE                      "Tap to continue..."
#define STRING_COINCIDENCE_EVENTS                   "Coincidence Events"
#define STRING_COUNTS_PER_HOUR_ABBREVIATION         "CPH"
#define STRING_DISABLE_THE                          "Disable the"
#define STRING_COSMIC_RAY_DETECTOR_QUESTION_MARK    "cosmic ray detector?"
#define STRING_YES                                  "Yes"
#define STRING_NO                                   "No"
#define STRING_RADIATION_HISTORY_CPM                "Radiation history (CPM)"
#define STRING_TRUE_RNG                             "True RNG"
#define STRING_INFO                                 "Info"
#define STRING_NOT_YET_AVAILABLE                    "Not yet available"
#define STRING_HOTSPOT_SETTINGS                     "Hotspot settings"
#define STRING_ENABLE_HOTSPOT                       "Enable hotspot"
#define STRING_HOTSPOT_NAME                         "Hotspot name"
#define STRING_HOTSPOT_PASSWORD                     "Hotspot password"
#define STRING_IP_ADDRESS                           "IP address"
#define STRING_NOT_CONNECTED                        "Not connected"
#define STRING_CONNECTING                           "Connecting..."
#define STRING_WIFI_SETTINGS                        "WiFi settings"
#define STRING_ENABLE_WIFI                          "Enable WiFi"
#define STRING_WIFI_NAME                            "WiFi name"
#define STRING_WIFI_PASSWORD                        "WiFi password"
#define STRING_ASTERISKS                            "********"
#define STRING_SYSTEM_SETTINGS                      "System settings"
#define STRING_SD_CARD_MOUNTED                      "SD card mounted"
#define STRING_LOG_TO_SERIAL_CONSOLE                "Log to serial console"
#define STRING_LOG_TO_SD_CARD                       "Log to SD card"
#define STRING_LOG_DATA                             "Log data"
#define STRING_LOG_EVENT_MESSAGES                   "Log event messages"
#define STRING_LOG_SYSTEM_INFO                      "Log system info"
#define STRING_FIRMWARE_VERSION                     "Firmware version"
#define STRING_SYSTEM_UPTIME                        "System uptime"
#define STRING_MINUTES_ABBREVIATION                 "min"
#define STRING_FREE_MEMORY_BYTES                    "Free memory (Bytes)"
#define STRING_RESTART                              "Restart"
#define STRING_RESET                                "Reset"

#endif